"""create user model

Revision ID: 046c90d91bb1
Revises: f8604c186b30
Create Date: 2024-03-02 15:08:37.310392

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '046c90d91bb1'
down_revision = 'f8604c186b30'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('is_staff', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('is_staff')
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###
